### ISSUE TITLE
Was passiert von User in DAPNET schon existiert?

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Import#1]
Ich hatte neulich den Fall, dass dein bereits eingetragener User überschrieben wurde? Kann das hier passieren?

**Comment by menzerath** [comment]
Insofern der Username bereits vorhanden ist, sollte eine Nachricht ("Your callsign is already imported.") angezeigt werden.
Dabei werden keinerlei Daten verändert.
