### ISSUE TITLE
Import defekt: Class 'SQLite3' not found

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Import#2]
``[Thu Sep 07 10:08:45.828064 2017] [:error] [pid 29007] [client 134.130.90.17:55239] PHP Fatal error:  Uncaught Error: Class 'SQLite3' not found in /srv/dapnet-import/website/index.php:12\nStack trace:\n#0 {main}\n  thrown in /srv/dapnet-import/website/index.php on line 12, referer: http://www.hampager.de/dapnet-import/index.php``

**Comment by menzerath** [comment]
Wurde auf dem Server vor Kurzem PHP 7 installiert? Es fehlte das `php7.0-sqlite3` Paket...

**Comment by dh3wr** [comment]
Ja genau. Danke
