### ISSUE TITLE
Callsign in Kleinbuchstaben?

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Import#4]
Wir das eingegeben Callsign in Kleinbuchstaben umgewandelt, bevor es zur REST-API geschickt wird zum Anlegen der Einträge?

**Comment by menzerath** [comment]
Ja, die Einträge liegen in Kleinbuchstaben in der Datenbank.
Siehe auch https://github.com/DecentralizedAmateurPagingNetwork/Import/blob/master/import-user-db.js#L59 und https://github.com/DecentralizedAmateurPagingNetwork/Import/blob/master/import-callsigns-db.js#L56.

**Comment by dh3wr** [comment]
ok, danke
